### ISSUE TITLE
change distance to take references

### ISSUE THREAD

**Issue by porky11** [brendanzab/cgmath#393]
`distance` (and `distance2`) function of the `MetricSpace` trait take types as parameters and consume them. This requires the types to implement `Copy` to work, or to clone them explicitely. Copying for just calculating the distance is an unneccessary overhead, especially when using custom types, which don't implement `Copy`

**Comment by DaseinPhaos** [comment]
The problem set that this crate is dealing with *only* covers cg-related vector types, which are all kinda small, (`Vector4<f64>` being the biggest, yet even that consumes only 256 bits). It is quite reasonable to consider these vectors to be small enough such that they should all implement `Copy` and being passed around by values whenever possible.

Under these presumptions, I don't think we should change the current design mentioned here. Unless being proven otherwise ( by a dedicated benchmark or something), I'd assume that passing values around would be more register-friendly and result in more efficient operations.

**Comment by brendanzab** [comment]
Yeah - this is a kind of hard thing with designing traits for Rust - sometimes it is better to copy a small data structure, so it is hard to be generic :(
